[project]
name = "cookiecutter-template"
version = "0.1.0"
description = "Herramientas para desarrollar y probar la cookiecutter {{ cookiecutter.project_slug }}."
authors = [
  { name = "Tu Nombre", email = "tucorreo@ejemplo.com" }
]
requires-python = ">=3.8"
dependencies = [
  "cookiecutter"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
