[project]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.project_version }}"
description = "{{ cookiecutter.project_description }}"
authors = [
  "{{ cookiecutter.project_author_name }}"
]
readme = "README.md"
requires-python = ">= {{ cookiecutter.python_version }}"
license = {text = "{{ cookiecutter.project_open_source_license if cookiecutter.project_open_source_license != 'No license file' else ''}}"}
dependencies = [
  "black",
  "invoke",
  "jupyter",
  "jupyterlab",
  "matplotlib",
  "nbdime",
  "numpy",
  "pandas",
  "plotly",
  "pyjanitor",
  "pyprojroot",
  "seaborn",
  {% if cookiecutter.project_packages == "All" -%}
  "keras",
  "lightgbm",
  "missingno",
  "pandas-flavor",
  "pandas-profiling",
  "pylint",
  "pyspark",
  "python-dotenv",
  "scikit-learn",
  "statsmodels",
  "tensorflow",
  {% endif -%}
]

[tool.setuptools]
packages = ["{{ cookiecutter.project_slug }}"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
