[project]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.project_version }}"
description = "{{ cookiecutter.project_description }}"
authors = [
  { name = "{{ cookiecutter.project_author_name }}" }
]
readme = "README.md"
requires-python = ">= {{ cookiecutter.python_version }}"
license = { text = "{{ cookiecutter.project_open_source_license if cookiecutter.project_open_source_license != 'No license file' else '' }}" }
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "plotly",
    "jupyter",
    "jupyterlab",
]

[project.optional-dependencies]
dev = [
    "black",
    "invoke",
    "nbdime",
    "pylint",
]

ml = [
    "scikit-learn",
    "keras",
    "tensorflow",
    "lightgbm",
    "statsmodels",
    "pyjanitor",
    "pandas-flavor",
    "pandas-profiling",
    "pyspark",
    "python-dotenv",
    "missingno",
]

[tool.setuptools]
packages = ["{{ cookiecutter.project_slug }}"]

[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"
